version: 1

kind: Service

metadata:
  name: simple-service

spec:
  containers:
    - name: users-service
      containerName: users
      dockerfile: some_path
      image: some_path
      ports:
        - 8080:8080
        - 50051:50051
      env:
        run: run-command
        clean: clean-command
        db_url: postgres:5432
      replicas: 3
      healthPath: /health

    - name: auth-service
      containerName: auth
      dockerfile: some_path
      image: some_path
      ports:
        - 8081:8081
        - 50052:50052
      env:
        db_url: postgres:5432
      replicas: 6
      healthPath: /health

dependsOn:
  - default.Server.simple-server